name: Deploy Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]

concurrency:
  group: pages-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare public folder
        run: |
          # Remove old public folder and recreate
          rm -rf public
          mkdir -p public
          # Copy site files into public, excluding workflow configs, git data and node_modules
          rsync -av --exclude='.github' --exclude='.git' --exclude='node_modules' --exclude='scripts' ./ public/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
