
name: Generate Languages Summary
permissions:
  contents: write

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps (none required)
        run: echo "No deps"

      - name: Run language aggregation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: node ./scripts/generate-languages.js

      - name: Commit & Push languages.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/js/languages.json
          git commit -m "chore(ci): update languages.json [skip ci]" || echo "No changes to commit"
          git push
